import type { RepoScan, ScannedFile } from "./types.js";

export type RenderAgentsOptions = {
  linkContext?: boolean;
  maxBytes?: number;
};

export function renderAgents(scan: RepoScan, options: RenderAgentsOptions = {}): string {
  const maxBytes = options.maxBytes ?? scan.config.agents.maxBytes;
  const linkContext = options.linkContext ?? scan.config.agents.linkContext;
  const importantFiles = agentRelevantFiles(scan);
  const lines: string[] = [];

  lines.push("# AGENTS.md");
  lines.push("");
  lines.push("## Repository Overview");
  lines.push("");
  lines.push("- This file was generated by `ai-context-pack` to help Codex and other coding agents onboard quickly.");
  if (scan.techStack.length > 0) lines.push(`- Detected stack: ${scan.techStack.join(", ")}`);
  lines.push(`- Text files scanned: ${scan.stats.scannedTextFiles}`);
  lines.push(`- Important files detected: ${scan.stats.keyFiles}`);
  if (linkContext) {
    lines.push(`- For the detailed generated context report, read \`${scan.config.output.markdown}\`.`);
  }
  lines.push("");

  const layout = renderLayout(importantFiles);
  if (layout.length > 0) {
    lines.push("## Repository Layout");
    lines.push("");
    for (const item of layout) lines.push(`- \`${item.path}\` - ${item.reason}`);
    lines.push("");
  }

  const commandLines = renderCommands(scan);
  if (commandLines.length > 0) {
    lines.push("## Commands");
    lines.push("");
    lines.push(...commandLines);
    lines.push("");
  }

  const renderedImportantFiles = importantFiles.slice(0, 18);
  if (renderedImportantFiles.length > 0) {
    lines.push("## Important Files");
    lines.push("");
    for (const file of renderedImportantFiles) {
      lines.push(`- \`${file.path}\` - ${summarizeFile(file)}`);
    }
    lines.push("");
  }

  if (scan.envVars.length > 0) {
    lines.push("## Environment Variables");
    lines.push("");
    lines.push("- The scanner found these environment variable names. Confirm required values before running commands.");
    for (const envVar of scan.envVars.slice(0, 40)) lines.push(`- \`${envVar}\``);
    lines.push("");
  }

  lines.push("## Agent Working Agreements");
  lines.push("");
  lines.push("- Prefer existing project patterns and dependencies before adding new ones.");
  lines.push("- Run the smallest relevant validation command after changing code.");
  lines.push("- For current Git diff context, run `ai-context-pack diff` instead of relying on this durable instructions file.");
  lines.push("- If a command or setup step is missing, update this file or the README with the discovered workflow.");
  lines.push("- Keep generated context files such as `AI_CONTEXT.md` out of source control unless the project explicitly wants them committed.");
  lines.push("");

  return limitBytes(`${lines.join("\n").trim()}\n`, maxBytes);
}

function agentRelevantFiles(scan: RepoScan): ScannedFile[] {
  const agentsPath = scan.config.output.agents.toLowerCase();
  return scan.importantFiles.filter((file) => file.path.toLowerCase() !== agentsPath);
}

function renderLayout(files: ScannedFile[]): Array<{ path: string; reason: string }> {
  const seen = new Set<string>();
  const items: Array<{ path: string; reason: string }> = [];

  for (const file of files) {
    const top = topLevel(file.path);
    if (!top || seen.has(top)) continue;
    const reason = file.reasons[0] ?? file.language ?? "contains project signals";
    items.push({ path: top, reason });
    seen.add(top);
    if (items.length >= 12) break;
  }

  return items;
}

function renderCommands(scan: RepoScan): string[] {
  const order = ["install", "dev", "build", "test", "lint"] as const;
  const labels: Record<(typeof order)[number], string> = {
    install: "Install",
    dev: "Run locally",
    build: "Build",
    test: "Test",
    lint: "Lint/check"
  };
  const lines: string[] = [];

  for (const key of order) {
    const commands = scan.commands[key] ?? [];
    if (commands.length === 0) continue;
    lines.push(`- ${labels[key]}: ${commands.slice(0, 4).map((command) => `\`${command}\``).join(", ")}`);
  }

  return lines;
}

function summarizeFile(file: ScannedFile): string {
  const summary = file.summary?.replace(/\s+/g, " ").trim();
  if (summary) return summary.slice(0, 220);
  if (file.reasons.length > 0) return file.reasons.join(", ");
  if (file.symbols.length > 0) return `Defines ${file.symbols.slice(0, 8).join(", ")}`;
  return "important project signal";
}

function topLevel(filePath: string): string | undefined {
  const parts = filePath.split("/");
  if (parts.length === 0 || !parts[0]) return undefined;
  return parts.length === 1 ? parts[0] : `${parts[0]}/`;
}

function limitBytes(value: string, maxBytes: number): string {
  const bytes = Buffer.byteLength(value, "utf8");
  if (bytes <= maxBytes) return value;

  const fullSuffix = "\n\n<!-- Truncated by ai-context-pack to fit AGENTS.md size limit. Read AI_CONTEXT.md for the full context. -->\n";
  const suffix = Buffer.byteLength(fullSuffix, "utf8") <= maxBytes
    ? fullSuffix
    : "\n<!-- Truncated by ai-context-pack. -->\n";
  const suffixBytes = Buffer.byteLength(suffix, "utf8");
  if (suffixBytes > maxBytes) return "";

  const target = maxBytes - suffixBytes;
  let output = "";

  for (const char of value) {
    if (Buffer.byteLength(output + char, "utf8") > target) break;
    output += char;
  }

  return `${output.trimEnd()}${suffix}`;
}
